# Generated by Django 5.2.12 on 2026-03-23 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('primary_pattern', models.CharField(blank=True, choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('CORE', 'Core'), ('FULL_BODY', 'Full Body'), ('CARDIO', 'Cardio'), ('OTHER', 'Other')], help_text='Optional suggestion only, not a hard rule.', max_length=20, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null means global/system exercise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('focus', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('UPPER', 'Upper'), ('LOWER', 'Lower'), ('FULL_BODY', 'Full Body'), ('ARMS', 'Arms'), ('SHOULDERS', 'Shoulders'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExercisePoolItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_items', to='fitness.exercise')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fitness.exercisepool')),
            ],
            options={
                'ordering': ['pool_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('focus', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('UPPER', 'Upper'), ('LOWER', 'Lower'), ('FULL_BODY', 'Full Body'), ('ARMS', 'Arms'), ('SHOULDERS', 'Shoulders'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source_pool', models.ForeignKey(blank=True, help_text='Optional pool used as recommendation source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='fitness.exercisepool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_entries', to='fitness.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='fitness.workoutsession')),
                ('source_pool_item', models.ForeignKey(blank=True, help_text='Optional source recommendation item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_entries', to='fitness.exercisepoolitem')),
            ],
            options={
                'ordering': ['session_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('set_type', models.CharField(blank=True, choices=[('TOP', 'Top'), ('BACKOFF', 'Backoff'), ('STRAIGHT', 'Straight'), ('AMRAP', 'AMRAP'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.workoutsessionexercise')),
            ],
            options={
                'ordering': ['session_exercise_id', 'set_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['slug'], name='idx_exercise_slug'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['primary_pattern'], name='idx_exercise_pattern'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['created_by', 'is_active'], name='idx_exercise_creator_active'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(fields=('created_by', 'slug'), name='uniq_exercise_created_by_slug'),
        ),
        migrations.AddIndex(
            model_name='exercisepool',
            index=models.Index(fields=['user', 'focus'], name='idx_pool_user_focus'),
        ),
        migrations.AddIndex(
            model_name='exercisepool',
            index=models.Index(fields=['user', 'is_active'], name='idx_pool_user_active'),
        ),
        migrations.AddConstraint(
            model_name='exercisepool',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_exercise_pool_user_name'),
        ),
        migrations.AddIndex(
            model_name='exercisepoolitem',
            index=models.Index(fields=['pool', 'sequence'], name='idx_pool_item_pool_sequence'),
        ),
        migrations.AddIndex(
            model_name='exercisepoolitem',
            index=models.Index(fields=['exercise'], name='idx_pool_item_exercise'),
        ),
        migrations.AddConstraint(
            model_name='exercisepoolitem',
            constraint=models.UniqueConstraint(fields=('pool', 'sequence'), name='uniq_pool_item_pool_sequence'),
        ),
        migrations.AddConstraint(
            model_name='exercisepoolitem',
            constraint=models.UniqueConstraint(fields=('pool', 'exercise'), name='uniq_pool_item_pool_exercise'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'status'], name='idx_session_user_status'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'focus'], name='idx_session_user_focus'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'scheduled_date'], name='idx_session_user_sched_date'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'started_at'], name='idx_session_user_started_at'),
        ),
        migrations.AddIndex(
            model_name='workoutsessionexercise',
            index=models.Index(fields=['session', 'sequence'], name='idx_session_exercise_sequence'),
        ),
        migrations.AddIndex(
            model_name='workoutsessionexercise',
            index=models.Index(fields=['exercise'], name='idx_session_exercise_exercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutsessionexercise',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_session_exercise_session_sequence'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['session_exercise', 'set_order'], name='idx_wset_se_order'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'set_order'), name='uniq_workout_set_session_exercise_order'),
        ),
    ]
