# Generated by Django 5.2.12 on 2026-03-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercise',
            name='uniq_exercise_created_by_slug',
        ),
    ]
