# Generated by Django 5.2.13 on 2026-05-01 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_exercise_uniq_exercise_created_by_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Client-generated idempotency key for mobile/offline create.', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker for sync-aware top-level objects.', null=True),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Monotonic server-side version for sync/conflict detection.'),
        ),
        migrations.AddField(
            model_name='workoutsessionexercise',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Client-generated idempotency key for mobile/offline create.', null=True),
        ),
        migrations.AddField(
            model_name='workoutsessionexercise',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Monotonic server-side version for sync/conflict detection.'),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Client-generated idempotency key for mobile/offline create.', null=True),
        ),
        migrations.AddField(
            model_name='workoutset',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Monotonic server-side version for sync/conflict detection.'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'updated_at'], name='idx_session_user_updated'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'deleted_at'], name='idx_session_user_deleted'),
        ),
        migrations.AddIndex(
            model_name='workoutsessionexercise',
            index=models.Index(fields=['session', 'updated_at'], name='idx_session_exercise_updated'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['session_exercise', 'updated_at'], name='idx_wset_se_updated'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('user', 'client_uuid'), name='uniq_wsession_user_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='workoutsessionexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('session', 'client_uuid'), name='uniq_session_exercise_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('session_exercise', 'client_uuid'), name='uniq_workout_set_client_uuid'),
        ),
    ]
