# Generated by Django 5.2.13 on 2026-05-01 21:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_workoutsession_client_uuid_workoutsession_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutset',
            name='rpe',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
