# Generated by Django 5.2.12 on 2026-03-23 18:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('target_calories_base', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('activity_type', models.CharField(choices=[('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('WALKING', 'Walking'), ('HIKING', 'Hiking'), ('SWIMMING', 'Swimming'), ('OTHER', 'Other')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('calories_burned_est', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'date'], name='idx_activity_user_date'), models.Index(fields=['user', 'activity_type', 'date'], name='idx_activity_user_type_date')],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('diet_mode', models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('GLUTEN_FREE', 'Gluten Free'), ('LOW_CARB', 'Low Carb'), ('KETO', 'Keto'), ('HIGH_PROTEIN', 'High Protein'), ('CUSTOM', 'Custom')], max_length=20, null=True)),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, help_text='Sleep quality on a 1-5 scale.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('alcohol_consumed', models.BooleanField(default=False)),
                ('calories_planned', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_actual', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'date'], name='idx_daily_metric_user_date'), models.Index(fields=['date'], name='idx_daily_metric_date')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_daily_metric_user_date')],
            },
        ),
    ]
