# Generated by Django 5.2.13 on 2026-04-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_replace_alcohol_consumed_with_alcohol_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_type', models.CharField(choices=[('OVERVIEW', 'Overview'), ('ANALYTICS', 'Analytics')], max_length=20)),
                ('window_days', models.PositiveSmallIntegerField()),
                ('as_of_date', models.DateField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'snapshot_type', 'window_days'],
                'indexes': [models.Index(fields=['user', 'snapshot_type', 'window_days'], name='idx_analytics_snapshot_lookup'), models.Index(fields=['as_of_date'], name='idx_analytics_snapshot_as_of')],
                'constraints': [models.UniqueConstraint(fields=('user', 'snapshot_type', 'window_days'), name='uniq_analytics_snapshot_user_type_window')],
            },
        ),
    ]
