# Generated by Django 5.2.13 on 2026-04-13 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0003_analyticssnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssnapshot',
            name='last_enqueued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analyticssnapshot',
            name='status',
            field=models.CharField(choices=[('FRESH', 'Fresh'), ('QUEUED', 'Queued'), ('ERROR', 'Error')], default='QUEUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['status'], name='idx_analytics_snapshot_status'),
        ),
    ]
