# Generated by Django 5.2.13 on 2026-05-01 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_profile_avatar_profile_bio_profile_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='client_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Client-generated idempotency key for mobile/offline create.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete marker for sync-aware top-level objects.', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Monotonic server-side version for sync/conflict detection.'),
        ),
        migrations.AddField(
            model_name='dailymetric',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Monotonic server-side version for sync/conflict detection.'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'updated_at'], name='idx_activity_user_updated'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', 'deleted_at'], name='idx_activity_user_deleted'),
        ),
        migrations.AddIndex(
            model_name='dailymetric',
            index=models.Index(fields=['user', 'updated_at'], name='idx_daily_metric_user_updated'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('user', 'client_uuid'), name='uniq_activity_user_client_uuid'),
        ),
    ]
